name: Run trigger

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Close
        run: |
          echo "Closing PR"
          echo "Closing PR" >> $GITHUB_OUTPUT
          gh pr close --comment "Auto-closing pull request" --delete-branch ${{ github.event.pull_request.number }}