name: running-trigger

on:
  pull_request_target:
    types: [opened, updated, synchronize]
    branches:
      - main

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Close
        run: |
          gh pr close --comment "Auto-closing pull request" --delete-branch ${{ github.event.pull_request.number }}
        env: GH_TOKEN: ${{ secrets.GH_TOKEN }}